vulnerabilities:
  - id: CVE-2023-24538
    paths:
      - "usr/local/bin/gosu"
    statement: "gosu not use html/template"

  - id: CVE-2023-24540
    paths:
      - "usr/local/bin/gosu"
    statement: "gosu not use html/template"

  - id: CVE-2024-24790
    paths:
      - "usr/local/bin/gosu"
    statement: "gosu not use net/netip"

  - id: CVE-2025-24813 # https://avd.aquasec.com/nvd/cve-2025-24813
    statement: "Upstream code not updated, risk accepted"

  - id: CVE-2016-1000027 # https://avd.aquasec.com/nvd/cve-2016-1000027
    statement: "Functionality not used, risk accepted"

  - id: CVE-2022-23806
    paths:
      - "build/percona-toolkit-3.x/util/mysql_random_data_load"
    statement: "only used in test"

  - id: CVE-2023-24538
    paths:
      - "build/percona-toolkit-3.x/util/mysql_random_data_load"
    statement: "only used in test"

  - id: CVE-2023-24540
    paths:
      - "build/percona-toolkit-3.x/util/mysql_random_data_load"
    statement: "only used in test"

  - id: CVE-2024-24790
    paths:
      - "build/percona-toolkit-3.x/util/mysql_random_data_load"
    statement: "only used in test"

  - id: CVE-2020-15999

  - id: CVE-2019-12900

  - id: CVE-2019-14697

  - id: CVE-2019-8457  