name: Build and Push Images
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'which docker build to run'
        required: true
        type: string
      tag:
        description: 'tag'
        required: true
        type: string

env:
  ONLINE_REGISTER: ghcr.io/ksmartdata
  BUILD_PLATFORM: linux/amd64,linux/arm64

jobs:
  common-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Build && Push
        uses: docker/build-push-action@v6.18.0
        with:
          context: ./images/${{ inputs.job }}
          file: ./images/${{ inputs.job }}/Dockerfile
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          platforms: ${{ env.BUILD_PLATFORM }}
          tags: ${{ env.ONLINE_REGISTER }}/${{ inputs.job }}:${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Build from ${{ github.ref }} ${{ github.sha }}
