name: Build and Push Images
run-name: Build ${{ inputs.job }}:${{ inputs.tag }} by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      job:
        description: 'which docker build to run'
        required: true
        type: string
      tag:
        description: 'tag'
        required: true
        type: string
      build-args:
        description: 'build args'
        required: false
        type: string
      context:
        description: 'docker build context, defaults to ./images/<job>'
        required: false
        type: string
      dockerfile:
        description: 'dockerfile path, defaults to ./images/<job>/Dockerfile'
        required: false
        type: string

env:
  ONLINE_REGISTER: ghcr.io/ksmartdata
  BUILD_PLATFORM: linux/amd64,linux/arm64

permissions:
  contents: read
  packages: write

jobs:
  common-build-and-push:
    if: ${{ inputs.job != 'community-server' && inputs.job != 'community-router' }}
    runs-on: ubuntu-latest
    steps:
      - name: Git clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Build && Push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context || format('./images/{0}', inputs.job) }}
          file: ${{ inputs.dockerfile || format('./images/{0}/Dockerfile', inputs.job) }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push: true
          platforms: ${{ env.BUILD_PLATFORM }}
          tags: ${{ env.ONLINE_REGISTER }}/${{ inputs.job }}:${{ inputs.tag }}
          labels: |
            org.opencontainers.image.source=https://github.com/ksmartdata/docker-images
            org.opencontainers.image.revision=${{ github.sha }}
          cache-from: type=gha
          build-args: ${{ inputs.build-args }}
          cache-to: type=gha,mode=max
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Build from ${{ github.ref }} ${{ github.sha }}

  copy-mysql-community-images:
    if: ${{ inputs.job == 'community-server' || inputs.job == 'community-router' }}
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy arch images
        run: |
          source_repository="container-registry.oracle.com/mysql/${{ inputs.job }}"
          target_repository="${{ env.ONLINE_REGISTER }}/${{ inputs.job }}"

          docker pull --platform linux/amd64 "${source_repository}:${{ inputs.tag }}"
          docker pull --platform linux/arm64 "${source_repository}:${{ inputs.tag }}-aarch64"

          docker tag "${source_repository}:${{ inputs.tag }}" "${target_repository}:${{ inputs.tag }}-amd64"
          docker tag "${source_repository}:${{ inputs.tag }}-aarch64" "${target_repository}:${{ inputs.tag }}-arm64"

          docker push "${target_repository}:${{ inputs.tag }}-amd64"
          docker push "${target_repository}:${{ inputs.tag }}-arm64"

      - name: Create and push manifest image
        run: |
          target_repository="${{ env.ONLINE_REGISTER }}/${{ inputs.job }}"
          target_image="${target_repository}:${{ inputs.tag }}"

          docker manifest rm "${target_image}" || true
          docker manifest create \
            "${target_image}" \
            "${target_repository}:${{ inputs.tag }}-amd64" \
            "${target_repository}:${{ inputs.tag }}-arm64"
          docker manifest annotate "${target_image}" "${target_repository}:${{ inputs.tag }}-amd64" --os linux --arch amd64
          docker manifest annotate "${target_image}" "${target_repository}:${{ inputs.tag }}-arm64" --os linux --arch arm64
          docker manifest push "${target_image}"

      - name: Inspect manifest image
        run: docker manifest inspect "${{ env.ONLINE_REGISTER }}/${{ inputs.job }}:${{ inputs.tag }}"
